In [1]:
import numpy as np

In [2]:
my_arr = np.arange(10000000)
my_list = list(range(10000000))


In [3]:
%time for _ in range(10):my_arr2 = my_arr *2
%time for _ in range(10):my_list2 = my_list *2

CPU times: user 211 ms, sys: 47 ms, total: 258 ms
Wall time: 116 ms
CPU times: user 546 ms, sys: 250 ms, total: 796 ms
Wall time: 797 ms


In [4]:
data = np.array([1,2,3,4,5])
data

array([1, 2, 3, 4, 5])

In [5]:
type(data)

numpy.ndarray

In [6]:
data?


Type:        ndarray
String form: [1 2 3 4 5]
Length:      5
File:        /opt/anaconda3/lib/python3.12/site-packages/numpy/__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object t

In [7]:
data.dtype

dtype('int64')

In [8]:
new_data = data.astype(np.float64)

In [9]:
new_data.dtype, new_data

(dtype('float64'), array([1., 2., 3., 4., 5.]))

In [10]:
data.shape

(5,)

In [11]:
data.size

5

In [12]:
data.ndim

1

In [13]:
data1 = np.array([1,2,3,4],dtype = float)
data1

array([1., 2., 3., 4.])

In [14]:
data1.dtype

dtype('float64')

In [15]:
data2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
data2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
data3 = np.array([[1, 3], [4, 5, 6], [7, 8, 9]], dtype=object)

In [18]:
data3

array([list([1, 3]), list([4, 5, 6]), list([7, 8, 9])], dtype=object)

In [19]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.eye(4,5,dtype = int, k=2)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [23]:
da = np.arange(1,13)
da.shape = 3,4

In [24]:
da

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
da1 = np.ones(da.shape)
da1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
da2 = np.ones_like(da)
da2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [27]:
np.diag([1,2,3,4], k=1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [28]:
de = np.arange(16).reshape(4,4)
de

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
np.arange(1,100,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [30]:
np.linspace(1,100,20)


array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [31]:
a= np.arange(24).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [32]:
a.ndim, np.ndim(a)

(3, 3)

In [33]:
a.shape

(2, 3, 4)

In [34]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [35]:
a[1][1]

array([16, 17, 18, 19])

In [36]:
a[1][1][2]

18

In [37]:
a[1,1,2]

18

In [38]:
a[(1,1,2)]

18

In [39]:
c=np.linspace(0,100,20)

In [40]:
c[[0,1,2,4,5]]

array([ 0.        ,  5.26315789, 10.52631579, 21.05263158, 26.31578947])

In [41]:
f=np.arange(12).reshape((3,4))
f
f[0:2][:,0:2]

array([[0, 1],
       [4, 5]])

In [42]:
e = np.arange(10)
e[:6:2]

array([0, 2, 4])

In [43]:
e[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [44]:
c= np.arange(12).reshape(3,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
c[0,0] = 100
c

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [46]:
c[1] = 114
c

array([[100,   1,   2,   3],
       [114, 114, 114, 114],
       [  8,   9,  10,  11]])

In [47]:
a = np.arange(12)
b=np.reshape(a,(3,4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
b=a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
a.shape = (-1,1)
a


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [50]:
a= np.arange(9).reshape(3,3)
b= np.arange(12).reshape(3,4)
c= np.arange(15).reshape(3,5)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [53]:
np.hstack((a,b,c))

array([[ 0,  1,  2,  0,  1,  2,  3,  0,  1,  2,  3,  4],
       [ 3,  4,  5,  4,  5,  6,  7,  5,  6,  7,  8,  9],
       [ 6,  7,  8,  8,  9, 10, 11, 10, 11, 12, 13, 14]])

In [54]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
b=np.array([2,4,6,8,9])
b

array([2, 4, 6, 8, 9])

In [56]:
a+b

array([[ 2,  5,  8, 11, 13],
       [ 7, 10, 13, 16, 18]])

In [57]:
np.array([3,4,5])>np.array([1,4,9])

array([ True, False, False])

In [58]:
alpha = np.linspace(-1,1,11)
y= np.sin(np.pi*alpha)
y

array([-1.22464680e-16, -5.87785252e-01, -9.51056516e-01, -9.51056516e-01,
       -5.87785252e-01,  0.00000000e+00,  5.87785252e-01,  9.51056516e-01,
        9.51056516e-01,  5.87785252e-01,  1.22464680e-16])